import unittest
from UnitTests.ApproximateNormalTableTests import ApproximateNormalTableTests
from UnitTests.ScipPyTDistributionTests import SciPyTDistributionTests
from UnitTests.BinomialDistributionTests import BinomialDistributionTests
from UnitTests.BootstrappedCentralValueAnalyzerTests import BootstrappedCentralValueAnalyzerTests
from UnitTests.NormalCentralValueAnalyzerTests import NormalCentralValueAnalyzerTests
from UnitTests.SciPyChiSquaredDistributionTests import SciPyChiSquaredTests
from UnitTests.NormalBinomialAnalyzerTests import NormalBinomialAnalyzerTests
from UnitTests.SampleUtilitiesTests import SampleUtilitiesTests
from UnitTests.CategoricalSampleUtilitiesTests import CategoricalSampleUtilitiesTests
from UnitTests.TDistributionCentralValueAnalyzerTests import TDistributionCentralValueAnalyzerTests
from UnitTests.NormalVarianceAnalyzerTests import NormalVarianceAnalyzerTests
from UnitTests.SciPyFDistributionTests import SciPyFDistributionTests
from UnitTests.NormalCentralValueComparerTests import NormalCentralValueComparerTests
from UnitTests.EqualVarianceNormalCentralValueComparerTests import EqualVarianceNormalCentralValueComparerTests
from UnitTests.PairedNormalCentralValueComparerTests import PairedNormalCentralValueComparerTests
from UnitTests.NormalVarianceComparerTests import NormalVarianceComparerTests

if __name__ == "__main__":
    unittest.main()
